### ISSUE TITLE
.po Avada Version = 5.1.6

### ISSUE THREAD

**Issue by lekiend** [Theme-Fusion/Localization-l10n#100]
Hello,
I see that .po files versions are for avada 5.1.6
"Project-Id-Version: Avada 5.1.6\n"

Last version is 5.9.1.

Are these files up to date ?
Don't you have a place like glotpress where users can share translations more easily ?

Is this page still up to date: https://theme-fusion.com/documentation/avada/translations/help-translating-avada/

Thank you

**Comment by lekiend** [comment]
I found this: https://www.transifex.com/themefusion/avada/languages/

It looks like translations are not up to date on transifex.

Thank you

**Comment by aristath** [comment]
> Are these files up to date ?

Yes, they are. The file headers just don't get auto-updated when we sync the translations using our [`grunt`](https://github.com/Theme-Fusion/Localization-l10n/blob/master/Gruntfile.js) task.

>  Don't you have a place like glotpress where users can share translations more easily ?

Right now the easiest way to share translations is to simply submit a pull-request on this repository. If for some reason you can't submit a pull-request with your .po file you can simply create a new ticket and upload your file here. :+1: 

> It looks like translations are not up to date on transifex.

We abandoned transifex a long time ago, translations there are stale and obsolete.

**Comment by lekiend** [comment]
Ok but your files on github are not fully translated.

French (fr-FR): 671 / 3344 (20%)
Dutch (nl-NL): 931 / 3344 (27%)

Many translations are missing.
Regards

**Comment by aristath** [comment]
> Ok but your files on github are not fully translated.

That's because translations are from the community, we don't translate the files ourselves. If we did, we'd need a team of 50+ people just to handle translations for all languages. Translations rely on user contributions. When one of our users translates a file to their language they can submit their changes here, we review them just to make sure they don't add anything inappropriate, and merge them.
If only 20% of the French files is translated that's because these are the parts that the French community deemed necessary to submit.
If you translate more strings, please feel free to submit them and we'll be more than happy to merge them. The only way community translations can work is if people submit their translations :+1:

**Comment by lekiend** [comment]
OK, I understand.

The process to share translations with the community is not really the best.
Github or support ticket are not so easy or time consuming process.

I'm sure that some people have made the work but they don't know they can share their translations with others.

You should maybe communicate a little more on this ;-). Or use a system like transifex.

**Comment by aristath** [comment]
I totally agree that the current contribution process for translations is not the best out there.
We've been discussing internally and trying to find a way to improve this process.
Transifex and other similar solutions are not viable for a community the size of Avada's, so we're still looking for the best way to handle these translations. We've been experimenting with GlotPress etc, once we have something solid we'll definitely migrate to some other solution.
Until then this github repository is the best we've got. Of course you can always just send your .po files via email by creating a support ticket as the [doc](https://theme-fusion.com/documentation/avada/translations/help-translating-avada/) mentions, and in that case we just update the language files with the submitted .po file ourselves.
