### ISSUE TITLE
Some strings are not localized in German localization de_DE

### ISSUE THREAD

**Issue by gasperphoenix** [Theme-Fusion/Localization-l10n#110]
After manual installation of the de_DE language files for Avada and Fusion Core most strings are translated to German but some are still not. In the Blog overview there are still English strings ("By", "Comments", "Categories", "Tags"). In the search results these strings are correctly translated.

I used POEdit to check if the strings are correctly translated and I found them along with the correct translation inside the Avada de_De file.

**Comment by aristath** [comment]
Hello @gasperphoenix,

Some translations come from Avada, others from Fusion-Builder and others from Fusion-Core.
Did you also add translations for these 2 plugins? You can get them all from this repository.

**Comment by gasperphoenix** [comment]
Hi @aristath,
yes, I copied all de_DE files for Avada and both plugins Fusion Core and Fusion Builder to the desired folders on my wordpress installation. As I mentioned most strings are correctly translated and only these are missing.

**Comment by aristath** [comment]
I can see that these strings are not translated in the `fusion-builder-de_DE` files, so that's probably why. Example: https://github.com/Theme-Fusion/Localization-l10n/blob/20fe62251dbd85fc1aaab542a9662a1bfa95d65f/fusion-builder/fusion-builder-de_DE.po#L8599-L8609
If these get translated you shouldn't have any issues.
Please note that translations are community-driven, so if someone has not already submitted translations for strings they are untranslated.
If you translate them you can submit a pull-request to add them here, or you can send updated translation files to support@theme-fusion.com and we'll include them.

**Comment by gasperphoenix** [comment]
I found the root cause for this issue - it can be closed. There are two different folders with the name of the plugin and a subfolder _languages_ below _wp-content_ but the translation will only work if you copy it in of of the folders.

Copying the language files in these folders does _not_ work:
.../wp-content/plugins/fusion-core/languages
.../wp-content/plugins/fusion-builder/languages

But copying both the language files of Fusion Core and Fusion Builder in this folder works and solves my issue:
.../wp-content/languages/plugins
