### ISSUE TITLE
Contact Info widget is not translating

### ISSUE THREAD

**Issue by tripatwhat** [Theme-Fusion/Localization-l10n#113]
Hello,

i've downloaded the whole zip with languages, uploaded theme and fusion German translations to the appropriate folders.

I can see that theme options are translated and fusion builder too, but contact info widget stays on English. For example, Phone: stands where the Telefon: should be.

When i check the language file with Poedit, translation is inside the file, but for some reason system doesn't load it.

Any ideas how to solve this?

Thanks

**Comment by aristath** [comment]
Hello @tripatwhat 

I'm terribly sorry for the delay here, we missed this comment.
The `Phone:` string exists both in Avada and Fusion-Core.
Did you check the translations for fusion-core? Widgets load their strings from the plugin, while the one in Avada is used for WooCommerce orders.

**Comment by tripatwhat** [comment]
Hello @aristath,

thank you for your reply. Both fusion-core and fusion-builder language files are uploaded to languages/plugins.

Regards

**Comment by aristath** [comment]
I can see that in fusion-core the `Phone:` is not translated: https://github.com/Theme-Fusion/Localization-l10n/blob/0e72913c10998db777ab6ac1e74c684a48e001ce/fusion-core/fusion-core-de_DE.po#L1084-L1085

That's probably why it doesn't appear translated to you.

You can submit your translation updates if you want and we will merge them so that your sites can all get the latest files. More information on how to contribute can be found on https://github.com/Theme-Fusion/Localization-l10n#how-to-contribute 👍

**Comment by tripatwhat** [comment]
Ah, ok, the translation is missing here. Now i can see it on website.

Cool, thx for your help.
