### ISSUE TITLE
Spanish translation for Fusion Builder?

### ISSUE THREAD

**Issue by shamank** [Theme-Fusion/Localization-l10n#121]
Hi. I just wanted to know why Fusion Core and Avada theme are 100% translated, but Fusion Builder is not. Maybe I'm missing something...? Thank you.

**Comment by aristath** [comment]
Hello @shamank.

Our translations are community-driven, meaning it is our users and community that contribute translations. If Fusion-Builder is missing translations for Spanish it's because none of our users have submitted translations for that yet.

If you translate some strings to Spanish you can submit your translated files either by creating a pull-request on this repository, or simply by sending an email to our support team - in which case we merge your translations manually.
This way the whole Spanish community will be able to benefit from your translations, just like you are benefiting from the translations of others in Avada & Fusion-Core. 👍

**Comment by shamank** [comment]
Oh ok! I didn't know these translations were driven by community. Since this is (I guess) an official Avada repository, I thought you people were doing the job. No prob then, I think I'll be able to contribute too. Thanks!

**Comment by maximus80** [comment]
Yeah, we collect the translations in our repo, but they are driven by our awesome community. We would be glad, if you contribute to the translations too, so thank you! :+1:
