### ISSUE TITLE
Swedish translation of Avada

### ISSUE THREAD

**Issue by loftreklam** [Theme-Fusion/Localization-l10n#122]
Here is a better translation of Avada 6.1 in Swedish. The one you have now is totally wrong translated on some main translations.

[Avada-sv_SE.zip](https://github.com/Theme-Fusion/Localization-l10n/files/3767515/Avada-sv_SE.zip)

**Comment by aristath** [comment]
Thank you for your translations @loftreklam!

They have been merged and the API response was updated so in a few minutes the update should show up on your dashboard.

One thing I changed though was to remove your email address from the file headers to avoid spam issues, privacy concerns etc. For that same reason I edited your post above and removed the zip file from there since it contained your contact info.
