### ISSUE TITLE
Woocommerce cart menu not translated

### ISSUE THREAD

**Issue by atroxix** [Theme-Fusion/Localization-l10n#153]
Hi.

I have added some missing translations to wp-content/languages/themes/Avada-et.po (and .mo) files using Loco Translate. It works okay, but the only issue is with the menu - when I refresh page I even see that the translated menu item for cart is flashed once in the correct language, but then switched back to "1 ITEM(S)". Also the "View Cart" and "Checkout" links in the submenu are not translated, also I've added translations for them with Loco Translate.

Any hints to where else should I add the translations to? Is some Javascript updating those links or what happens there? I can't figure this out...

**Comment by aristath** [comment]
Hello there @atroxix 

WooCommerce saves a cookie containing these strings, and there is some JS that updates the cart markup. My guess is that the cookie is just persisting after you translated those string and that's what is causing your issue since it will contain the previously untranslated strings.
Try resetting your browser cookies, that should fix the issue on your browser.

**Comment by atroxix** [comment]
Thank you! You're correct. I could have sworn that I tested it also with private browsing, but I guess I did it at some other point then :)

The issue is solved indeed.

**Comment by peakbecker** [comment]
I had the same issue and tried in a private browser, to no avail.

It turned out those strings were in a custom menu of my theme. I was finally able to translate them with Loco Translate.
