### ISSUE TITLE
Dutch translation results in error 

### ISSUE THREAD

**Issue by ghulstr** [Theme-Fusion/Localization-l10n#255]
displaying a post with comments and ability to post comment result in a fatal error if site language is Nederlands (dutch).

if reset ito english (us) then the error is gone.

see snapshot
![avada error translation NL](https://github.com/user-attachments/assets/9596da91-668d-47df-a060-ac6c95b82fab)

Cannot find the culprit :(

**Comment by maximus80** [comment]
There is a translation error in the corresponding translation string in the Dutch language file, which is why you are getting the error. I have updated the translation file in our repo. Here is the zip, of both the .po and the .mo file. If you replace the .mo file in your project, it should work fine.
[fusion-builder-nl_NL.zip](https://github.com/user-attachments/files/16657429/fusion-builder-nl_NL.zip)
