### ISSUE TITLE
Fusion Bilder localization

### ISSUE THREAD

**Issue by Alexey666** [Theme-Fusion/Localization-l10n#45]
Dear friends!
Please help I need fusion-builder-ru_RU.mo fusion-builder-ru_RU.ro translated into russian.
After i downloud them from https://github.com/Theme-Fusion/Localization-l10n

![232323](https://cloud.githubusercontent.com/assets/12021450/24818538/9d4a76e0-1be9-11e7-9bec-822151ea1974.png)

Best regardes,
Alex

**Comment by lukeabeck** [comment]
Hi @Alexey666, can you tell us ...

- what operating system you are using.
- what version of POEdit you re using

Thanks!

@Theme-Fusion/developers this is the same reported issue as here I believe: https://github.com/Theme-Fusion/Localization-l10n/issues/39

**Comment by Alexey666** [comment]
Win 10 / poedit 2.0 (and I tried different system win 7) situation remaining the same. The file without translation. But if I translate a few words then upload to my site it shows just translated on my own.
(Hope you understand my poor English)
So I would be happy if you could send me those two files (translated) info.dokaf@gmail.com
Avada localization files are good only fusion builder brings trouble

**Comment by Alexey666** [comment]
Friends just say there is no translation in your language don't wait or some other information if you have.
Best regards,
Alex

**Comment by lukeabeck** [comment]
@Theme-Fusion/developers ?

**Comment by maximus80** [comment]
Hello @Alexey666,

sorry this took a bit until you get a reply. Because of the weekend andus being very busy at the moment, this took longer than expected.

In general our language repo is a public repo, where translations are driven by our user base. Using the repo every customer of Avada can

1. get all needed translation files for Avada, Fusion Builder and Fusion Core for his language, with updated translation strings after every update.

2. contribute to the translation of his own language. Depending on the language, there are .po files that have quite a lot strings translated already. Other languages currently only have a few strings translated.

I can see there are translated strings for Russian in the Avada .po file, but not in the Fusion Builder one. So in case of Russian, we would welcome it a lot, if you would commit your translation to the repo, so it becomes accessible to the community. Others may continue on it then so that it can grow over the time.

I hope that answers your question.

Cheers,
Mark

**Comment by Alexey666** [comment]
Ok) thanks for answering! So if I translate my self it'ok)

**Comment by aristath** [comment]
@Alexey666 yes, if you translate yourself it will work fine, and you can also [submit a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) so that others benefit from your translations. In time other users also submit pull-requests as well and the translations are enriched and completed easier by the community of our users.

Until then I'll go ahead and close this ticket. 👍
