### ISSUE TITLE
Wrong de-DE_formal translations

### ISSUE THREAD

**Issue by devr1** [Theme-Fusion/Localization-l10n#58]
There are some wrong translations in the file "Localization-l10n/Avada/Avada-de_DE_formal.po".
Formal means, that there shouldn't be ANY "Du/du" oder "Deine/deine" etc.

The most important parts are:

#: includes/class-avada-woocommerce.php:1140
msgid "You Have %d Item In Your Cart"
msgstr "Du hast %d Artikel im Warenkorb"
should be translated to: "Sie haben einen Artikel im Warenkorb"

and

#: includes/class-avada-woocommerce.php:1142
msgid "You Have %d Items In Your Cart"
msgstr "Du hast %d Artikel im Warenkorb"
should be translated to: "Sie haben %d Artikel im Warenkorb"

There are some more, but they are not as present these.

Thanks a lot

**Comment by aristath** [comment]
Hello there @devr1,

Is this still an issue? If it is, do you have an updated .po file with those fixes so that we may update the translations? These translations are powered by the community so I'd be more than happy to merge any fixes you may have for the `de-DE_formal` translation files, but we don't have in-house people for all languages, so any fixes will have to be committed by a member of the community. 👍

**Comment by robertcrouver** [comment]
Yes, I do: Where can I post the files?

**Comment by maximus80** [comment]
That is awesome! You can either create a pull request, or upload the zip file here, and we'll merge it in then :+1:

**Comment by aristath** [comment]
@robertcrouver thank you for sending the file, I have submitted the new translations and updated the both the `.mo` & `.po` files in the repository. 👍

**Comment by robertcrouver** [comment]
It‘s been a pleasure... an incredible feeling as an IT-idiot to find solutions with the help of you all! 👍
