### ISSUE TITLE
Requesting for Filipino translation

### ISSUE THREAD

**Issue by vinzruzell** [Theme-Fusion/Localization-l10n#68]
Hi.I would like to request for Filipino translation.

**Comment by aristath** [comment]
@vinzruzell hey there!
The translations are not built or maintained by Theme-Fusion, we simply allow our community to contribute their translations here so that others may benefit from them. If a user translates the .pot/.po files to Filipino they can then submit a pull-request here, we review the translations and then merge them so that the next user can have them.
If nobody has translated Filipino yet, you could perhaps help out by translating the language files in your language using [Poedit](https://poedit.net/) and then sending the translated files for the rest of the community 👍
