### ISSUE TITLE
Update German translation

### ISSUE THREAD

**Issue by wassereimer86** [Theme-Fusion/Localization-l10n#74]
[AvadaGer.zip](https://github.com/Theme-Fusion/Localization-l10n/files/2039480/AvadaGer.zip)

**Comment by mikka23** [comment]
Thanks for the submission.  We will get it checked out and merged in 👍

**Comment by m1chelangel0** [comment]
Hi @wassereimer86  

Thanks for checking in. Firstly, we appreciate and thank you for the updated translation. However, please note how this works. Once you submit this it is checked by our team and then added to Avada. This addition can then only be released with the theme package when we release a theme update. Your submission has not been forgotten.

We are releasing the next update for Avada (version 5.6) in the next few weeks, we do not, however, release a theme update because of a language file change only. 

Regarding the untranslated string, that does not seem to a reported issue. Please create a support ticket and let us know in detail what it is that you are referring to -> https://theme-fusion.com/support/ - or submit a bug report here -> https://theme-fusion.com/contact-us/

Thank you kindly

**Comment by wassereimer86** [comment]
Hi @m1chelangel0 

Thank your for the quick answer and the explanation. But the languages aren´t included in the theme, or am i wrong? I had to download the languages here on Github and upload them to "/wp-content/languages/themes/".

The string i´m talking about is "Save my name, email, and website in this browser for the next time I comment." (comments.php line 68). It´s not translated in the german language file. So the german users do have a english text in their comments section. That was the initial reason why i translated it and a bunch of other things.

I can´t open a new ticket. ;) "Your support period has expired, to reactivate your theme support please extend/renew your Envato item support as explained here."

**Comment by maximus80** [comment]
@wassereimer86 I have merged in your lang file updates. Thank you for doing the work, this is appreciated!

What @m1chelangel0 was referring to is, that we do ship the lang files with the Avada full package, that can be downloaded from you Envato profile (in the installable zip they are not included). And that package can only be updated within a theme update on ThemeForest.

Here, in this repo they canalways be updated. Sometimes it takes a bit, until a team memebre can review new submissions. In your case, this item did slip through the net a bit, so it took longer than it normally does. Sorry for that!

I'm closing this one out as done :+1:
